if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
	set(CXXINIT_WARNING_FLAGS
		"-Wall"
		"-Walloca"
		"-Wcast-align"
		"-Wcast-qual"
		"-Wconversion"
		"-Wctor-dtor-privacy"
		"-Wdeprecated-copy-dtor"
		"-Wdouble-promotion"
		"-Wenum-conversion"
		"-Wextra"
		"-Wextra-semi"
		"-Wfloat-equal"
		"-Wformat-overflow"
		"-Wformat=2"
		"-Wframe-larger-than=1048576"
		"-Wimplicit-fallthrough"
		"-Wmismatched-tags"
		"-Wmissing-braces"
		"-Wmultichar"
		"-Wno-unused-parameter"
		"-Wnon-virtual-dtor"
		"-Wnull-dereference"
		"-Wold-style-cast"
		"-Woverloaded-virtual"
		"-Wpedantic"
		"-Wpointer-arith"
		"-Wrange-loop-construct"
		"-Wshadow"
		"-Wsign-conversion"
		"-Wundef"
		"-Wuninitialized"
		"-Wunused"
		"-Wvla"
		"-Wwrite-strings"
	)

	if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
		list(PREPEND CXXINIT_WARNING_FLAGS
			"-U_FORTIFY_SOURCE"
			"-D_FORTIFY_SOURCE=3"
		)
	endif ()
elseif (MSVC)
	set(CXXINIT_WARNING_FLAGS
		"/sdl"
		"/guard:cf"
		"/utf-8"
		"/diagnostics:caret"
		"/w14165"
		"/w44242"
		"/w44254"
		"/w44263"
		"/w34265"
		"/w34287"
		"/w44296"
		"/w44365"
		"/w44388"
		"/w44464"
		"/w14545"
		"/w14546"
		"/w14547"
		"/w14549"
		"/w14555"
		"/w34619"
		"/w34640"
		"/w24826"
		"/w14905"
		"/w14906"
		"/w14928"
		"/w45038"
		"/wd4324"
		"/W4"
		"/permissive-"
		"/volatile:iso"
		"/Zc:inline"
		"/Zc:preprocessor"
		"/Zc:enumTypes"
		"/Zc:lambda"
		"/Zc:__cplusplus"
		"/Zc:externConstexpr"
		"/Zc:throwingNew"
		"/Zf"
		"/EHsc"
	)
endif ()

if (CXXINIT_WARNING_FLAGS)
	add_compile_options(${CXXINIT_WARNING_FLAGS})
endif ()